"""add timestamp index

Revision ID: ba8e55ffdf34
Revises: c623d2099041
Create Date: 2026-09-19 19:10:56.953024

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ba8e55ffdf34'
down_revision: str | Sequence[str] | None = 'c623d2099041'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_telemetry_timestamp', 'telemetry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_timestamp', table_name='telemetry')
    # ### end Alembic commands ###
